site_name: Python-Harmony Documentation  # Nombre de tu web
site_url: https://naililian.github.io/
repo_url: https://github.com/naililian/naililian.github.io

theme:
  name: material  # El mejor tema para documentación técnica
  palette:
    scheme: default # Modo oscuro (puedes cambiarlo a 'default' para claro)
    primary: indigo
  features:
    - navigation.sections
    - content.code.copy # Permite copiar código con un clic
    - toc.integrate  # Sidebar with table of contents

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src] # IMPORTANTE: Aquí va la carpeta donde está tu código .py
          options:
            show_source: true         # Muestra el código fuente si el usuario quiere
            show_root_heading: true   # Muestra el nombre del módulo/función
            show_category_heading: true

markdown_extensions:
  - tables
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.superfences
  - toc:
      permalink: true

extra_css:
  - stylesheets/api-docs.css

nav:
  - Inicio: index.md
  - Utils: api.md # Aquí es donde se "rellenará" el código automáticamente
  - Nodes_Attributes: nodes_attributes.md
