site_name: Python Harmony Documentation
site_url: https://naililian.github.io/python-harmony/
repo_url: https://github.com/naililian/naililian.github.io

theme:
  name: material
  palette:
    scheme: default
    primary: indigo
  features:
    - navigation.sections
    - content.code.copy
    - toc.follow  # Makes right TOC follow scroll

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            show_source: true
            show_root_heading: true
            show_category_heading: true

markdown_extensions:
  - tables
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.superfences
  - toc:
      permalink: true

extra_css:
  - stylesheets/custom.css

nav:
  - Home: index.md
  - Nodes Attributes: nodes_attributes.md
  - Actions: actions.md
